resolver: lts-12.7
packages:
- discrimination-ieee754
- proto-lens
- proto-lens-arbitrary
- proto-lens-discrimination
- proto-lens-optparse
- proto-lens-protobuf-types
- proto-lens-protoc
- proto-lens-runtime
- proto-lens-setup
# Internal packages, not to be released:
- proto-lens-benchmarks
- proto-lens-tests
- proto-lens-tests-dep
extra-deps:
- discrimination-0.3
- promises-0.3

ghc-options:
  "$locals": -Wall -Werror

extra-deps:
- Cabal-3.0.0.0
- cabal-doctest-1.0.7
- happy-1.19.11
