resolver: lts-5.12
packages:
- proto-lens
- proto-lens-setup
- proto-lens-arbitrary
- proto-lens-combinators
- proto-lens-optparse
- proto-lens-tests

# Allow our custom Setup.hs scripts to import Data.ProtoLens.Setup from the version of
# `proto-lens-setup` in stack's local DB.  This makes things simpler when developing
# `proto-lens` and `proto-lens-tests` at the same time.
#
# For more details, see:
# http://docs.haskellstack.org/en/latest/yaml_configuration/#explicit-setup-deps
explicit-setup-deps:
  "*": true
