name: person-proto

custom-setup:
  dependencies:
    - base
    - Cabal
    - proto-lens-protoc

extra-source-files: src/**/*.proto

library:
  dependencies:
    - base
    - proto-lens
    - proto-lens-protoc

  exposed-modules:
    - Proto.Person
    - Proto.Person'Fields
